version: "3.8"
services:
  master:
    build: .
    ports:
      - "5030:5030"
      - "8081:8081"
      - "9108:9108"
    environment:
      - VRM_PRODUCTION=1
      - VRM_API_TOKEN=testtoken
      - VRM_GPU_OVERALLOCATION=1.5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
