# mkdocs.yml
site_name: VR‑C Inference
repo_url: https://github.com/your‑org/vrc_inference
repo_name: vrc_inference
theme:
  name: material
  palette:
    primary: "primary"
    accent:  "secondary"
  font:
    text: Inter
    code: Fira Code
nav:
  - Accueil: index.md
  - API: api.md
  - Utilisation: quickstart.md
