#!/usr/bin/env python3
"""VRAMancer Swarm Config Generator.

Auto-detects local GPUs and generates an appropriate .env config file
for joining or creating a VRAMancer swarm.

Usage:
    python scripts/generate_swarm_config.py                    # auto-detect
    python scripts/generate_swarm_config.py --role master      # force master
    python scripts/generate_swarm_config.py --role worker --master-ip 192.168.1.100
    python scripts/generate_swarm_config.py --output config/my-node.env
"""

import argparse
import os
import sys
import socket
import platform
import secrets

# Allow running from repo root
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))


def detect_gpus():
    """Detect available GPUs and their VRAM."""
    gpus = []
    try:
        import torch
        if torch.cuda.is_available():
            for i in range(torch.cuda.device_count()):
                props = torch.cuda.get_device_properties(i)
                gpus.append({
                    "id": i,
                    "name": props.name,
                    "vram_mb": props.total_mem // (1024 * 1024),
                    "arch": f"sm_{props.major}{props.minor}",
                })
        elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            gpus.append({
                "id": "mps",
                "name": f"Apple Silicon ({platform.machine()})",
                "vram_mb": 0,  # Unified, not separately trackable
                "arch": "mps",
            })
    except ImportError:
        pass
    return gpus


def detect_local_ip():
    """Get the LAN IP address of this machine."""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 53))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "127.0.0.1"


def detect_nvme_path():
    """Find the best NVMe cache directory."""
    candidates = ["/var/lib/vramancer/cache", "/tmp/vramancer/cache"]
    if sys.platform == "darwin":
        candidates.insert(0, os.path.expanduser("~/Library/Caches/vramancer"))
    elif sys.platform == "win32":
        candidates.insert(0, os.path.join(os.environ.get("LOCALAPPDATA", "C:\\"), "vramancer", "cache"))

    for path in candidates:
        parent = os.path.dirname(path)
        if os.path.isdir(parent) and os.access(parent, os.W_OK):
            return path
    return candidates[-1]


def classify_power_profile(gpus):
    """Classify power profile based on GPU capabilities."""
    if not gpus:
        return "low_power"
    total_vram = sum(g["vram_mb"] for g in gpus)
    if total_vram > 20000:
        return "high_perf"
    elif total_vram > 8000:
        return "standard"
    return "low_power"


def generate_config(role, master_ip, gpus, output_path):
    """Generate the .env config file."""
    hostname = socket.gethostname()
    local_ip = detect_local_ip()
    nvme_path = detect_nvme_path()
    power = classify_power_profile(gpus)
    total_vram = sum(g["vram_mb"] for g in gpus if isinstance(g["vram_mb"], int))
    # Leave 10% headroom
    usable_vram = int(total_vram * 0.9) if total_vram else 0

    gpu_names = ", ".join(f"{g['name']} ({g['vram_mb']} MB)" for g in gpus) if gpus else "CPU only"
    cuda_ids = ",".join(str(g["id"]) for g in gpus if isinstance(g["id"], int))

    lines = [
        f"# VRAMancer Swarm — {hostname}",
        f"# GPUs: {gpu_names}",
        f"# Generated by generate_swarm_config.py",
        f"# Local IP: {local_ip}",
        "",
        f"VRM_NODE_ROLE={role}",
    ]

    if role == "master":
        lines.append("VRM_CLUSTER_MASTER=true")
        lines.append("VRM_API_PORT=5030")
    else:
        lines.append("VRM_API_PORT=5032")
        if master_ip:
            lines.append(f"VRM_CLUSTER_MASTER_IP={master_ip}")

    lines.append("")

    if cuda_ids:
        lines.append(f"VRM_CUDA_DEVICES={cuda_ids}")
        for i, g in enumerate(gpus):
            if isinstance(g["id"], int):
                tier = "L1" if i == 0 else "L2"
                lines.append(f"VRM_MEMORY_TIER_{tier}=cuda:{g['id']}")
    elif gpus and gpus[0].get("arch") == "mps":
        lines.append("VRM_MPS_DEVICE=0")
        lines.append("VRM_MEMORY_TIER_L1=mps:0")

    lines.extend([
        "",
        f"VRM_MAX_MEMORY_MB={usable_vram}",
        "",
        "# Network",
        "VRM_AITP_PORT=9109",
        "VRM_AITP_SENSING_PORT=9110",
        "VRM_CLUSTER_SECRET=CHANGE_ME_IN_PRODUCTION",
        "",
        f"VRM_NVME_CACHE_DIR={nvme_path}",
        "VRM_NVME_CACHE_MB=20000",
        "",
        "VRM_XDP_MODE=auto",
        f"VRM_POWER_PROFILE={power}",
        "",
        "# Security",
        "VRM_API_TOKEN=CHANGE_ME",
        "VRM_PRODUCTION=0",
    ])

    config_text = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config_text)

    print(f"Config written to: {output_path}")
    print(f"  Role:    {role}")
    print(f"  GPUs:    {gpu_names}")
    print(f"  VRAM:    {usable_vram} MB usable")
    print(f"  Power:   {power}")
    print(f"  IP:      {local_ip}")
    if role == "worker" and master_ip:
        print(f"  Master:  {master_ip}")
    print()
    print("Next steps:")
    print(f"  1. Edit {output_path} — set VRM_API_TOKEN and VRM_CLUSTER_SECRET")
    if role == "master":
        print(f"  2. Start: env $(cat {output_path} | grep -v '^#' | xargs) python -m vramancer")
    else:
        print(f"  2. Set VRM_CLUSTER_MASTER_IP if not already correct")
        print(f"  3. Start: env $(cat {output_path} | grep -v '^#' | xargs) python -m vramancer")


def main():
    parser = argparse.ArgumentParser(description="Generate VRAMancer swarm config")
    parser.add_argument("--role", choices=["master", "worker", "auto"], default="auto")
    parser.add_argument("--master-ip", help="Master node IP (for workers)")
    parser.add_argument("--output", "-o", default=None, help="Output .env file path")
    args = parser.parse_args()

    gpus = detect_gpus()

    # Auto-detect role: master if multi-GPU or no master specified
    role = args.role
    if role == "auto":
        role = "master" if len(gpus) >= 2 or not args.master_ip else "worker"

    # Default output path
    if args.output is None:
        hostname = socket.gethostname().lower().replace(" ", "-")
        args.output = f"config/{hostname}.env"

    generate_config(role, args.master_ip, gpus, args.output)


if __name__ == "__main__":
    main()
